#==== connect to mysql ======#
spring:
  application:
    name: refreshtokens
  datasource:
     url: jdbc:mysql://${MYSQL_HOSTNAME:localhost}:3306/refreshtokens
     username: root
     password: D@tabase123
     driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    #bootstrap-servers: localhost:29092
    #bootstrap-servers: localhost:29092,localhost:39092
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      auto-offset-reset: earliest
      group-id: refreshtokens
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1
      enable-auto-commit: false
      client-id: refreshtokens
    producer:
      client-id: refreshtokens
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 2
    listener:
      poll-timeout: 1800000
      concurrency: 1
      ack-mode: manual-immediate
  batch:
    initialize-schema: always
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /manage
      
refreshtokens:
  kafka:
    consumer-enabled: ${consumer-enabled:true}